server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodapp
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

logging.level:
  root: INFO
  com.example.crud: DEBUG
