name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Frontend Layer
        run: |
          cd frontend-api-service
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Build CRUD Layer
        run: |
          cd crud-data-service
          chmod +x gradlew
          ./gradlew clean build -x test

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Test Frontend Layer
        run: |
          cd frontend-api-service
          chmod +x gradlew
          ./gradlew test

      - name: Test CRUD Layer
        run: |
          cd crud-data-service
          chmod +x gradlew
          ./gradlew test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env variables
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_FRONTEND=ghcr.io/$OWNER/foodapp-frontend" >> $GITHUB_ENV
          echo "IMAGE_CRUD=ghcr.io/$OWNER/foodapp-crud" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Frontend Docker Image
        run: |
          cd frontend-api-service
          docker build -t $IMAGE_FRONTEND:latest -t $IMAGE_FRONTEND:$SHA_TAG .

      - name: Build CRUD Docker Image
        run: |
          cd crud-data-service
          docker build -t $IMAGE_CRUD:latest -t $IMAGE_CRUD:$SHA_TAG .

      - name: Push Frontend Image
        run: |
          docker push $IMAGE_FRONTEND:latest
          docker push $IMAGE_FRONTEND:$SHA_TAG

      - name: Push CRUD Image
        run: |
          docker push $IMAGE_CRUD:latest
          docker push $IMAGE_CRUD:$SHA_TAG
